monolog:

  handlers:
    main:
      type:      stream
      level:     warning
      formatter: codely.infrastructure.monolog.formatter.logstash
      channels:  ['!api']
    api_request:
      type:      stream
      path:      "%kernel.logs_dir%/%kernel.environment%.api.requests.log"
      level:     warning
      formatter: codely.infrastructure.monolog.formatter.logstash
      channels:  ['api']
    events:
      type:      stream
      path:      "%kernel.logs_dir%/%kernel.environment%.events.log"
      level:     error
      formatter: codely.infrastructure.monolog.formatter.logstash
      channels:  ['events']
  channels: ['api', 'events']


services:

  monolog.processor.codely_request:
    class: CodelyTv\Infrastructure\Monolog\Processor\CodelyTvRequestProcessor
    arguments:
      - '@request_stack'
    tags:
        - { name: monolog.processor, handler: api_request }

  codely.infrastructure.monolog.formatter.logstash:
    class: CodelyTv\Infrastructure\Monolog\Formatter\LogstashFormatter
    public: false
