framework:

  secret: '%secret%'
  router:
    resource: '%kernel.root_dir%/app/config/routing/_routing.yml'
    strict_requirements: '%kernel.debug%'
  templating:
    engines: ['twig']
  default_locale:  '%locale%'
  trusted_proxies: ~
  session:   ~
  fragments: ~
  http_method_override: true


sensio_framework_extra:

  view:    { annotations: true }
  router:  { annotations: true }
  request: { converters: false }
