services:

  codely.video.notification.repository:
    class: CodelyTv\Context\Video\Module\Notification\Infrastructure\Persistence\MySqlNotificationRepository
    arguments:
      - '@codely.video.infrastructure.database'

  codely.video.notification.notifier:
    alias: codely.video.notification.slack_notifier

  codely.video.notification.email_notifier:
    class: CodelyTv\Context\Video\Module\Notification\Infrastructure\Notifier\EmailNotifier
    arguments:
      - '%video_notification_email_username%'
      - '%video_notification_email_password%'
    public: false

  codely.video.notification.slack_notifier:
    class: CodelyTv\Context\Video\Module\Notification\Infrastructure\Notifier\SlackNotifier
    arguments:
      - '%slack_video_notification_hook_url%'
      - username: '%slack_video_notification_username%'
        channel: '%slack_video_notification_channel%'
    public: false
